default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: development_for_suorademokratia
  socket: /var/run/mysqld/mysqld.sock

test:
  <<: *default
  database: test_for_suorademokratia
  socket: /var/run/mysqld/mysqld.sock

production:
  <<: *default
  database: production_for_suorademokratia
  socket: /var/run/mysqld/mysqld.sock

staging:
  <<: *default
  database: staging_for_suorademokratia
  socket: /var/run/mysqld/mysqld.sock

  